name: dart_demo_web
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.0.0
  cupertino_icons: ^1.0.8
  http: ^0.13.5
  flutter_dotenv: ^5.0.2
  dwds: ^24.0.0 # Updated to support null safety

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env # Added .env as an asset

dependency_overrides:
  dwds: ^24.0.0 # Ensure dwds is at least version 24.0.0

